# Generated by Django 5.1 on 2024-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist',
            new_name='Watchlists',
        ),
    ]
