# Generated by Django 5.1 on 2024-08-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_rename_watchlist_watchlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamPlatform',
            new_name='StreamPlatforms',
        ),
    ]
