# Generated by Django 5.1 on 2024-08-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_rename_streamplatform_streamplatforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlists',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplatforms'),
            preserve_default=False,
        ),
    ]
